# Site settings
title: Luan Zanchet - Full Stack Developer
description: "Um blog sobre desenvolvimento"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://luanzanchet.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Luan Zanchet 
user_title: Luan Zanchet 
email: luuanzanchet@outlook.com
twitter_username: luanzanchet
github_username:  luanzanchet
gplus_username:  luanzanchet
linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: loremipsum
profile_picture: https://scontent.fcfc5-1.fna.fbcdn.net/v/t1.0-9/20915093_1560415287312085_8454587711293185646_n.jpg?_nc_cat=108&_nc_ht=scontent.fcfc5-1.fna&oh=7c8489dc77caa1fc3d5659e97c683217&oe=5D4941F1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/luanzanchet
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/luanzanchet
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
