# Site settings
title: Luan Zanchet - Full Stack Developer
description: "A developer blog"
baseurl: "" 
url: "https://luanzanchet.github.io" 

# User settings
username: Luan Zanchet
user_title: Luan Zanchet
email: luuanzanchet@outlook.com
twitter_username: luanzanchet
github_username:  luanzanchet
gplus_username:  luanzanchet
linkedin_public_url: luanzanchet # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: luanzanchet
profile_picture: https://media.licdn.com/dms/image/C4E03AQF1EYgT1qMtRw/profile-displayphoto-shrink_200_200/0?e=1555545600&v=beta&t=Xxh1fSk3DMVMTNzsBQ8HU64sjCJMTTAvZoen0atenpA

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/victorvoid
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/victorvoid
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
