# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Luan Zanchet
description: "A developer blog "
keywords: "Luan, Zanchet, Blog, Dev"
url: https://luanzanchet.github.io
baseurl: ""

google_analytics: UA-52446115-1
repo: http://github.com/luanzanchet/luanzanchet.github.io
disqus_shortname: "luanzanchet"
disqus_site_shortname: "luanzanchet"

# Author settings
author:
  name: Luan Zanchet
  job: Full Stack Developer
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb: /images/author.jpg
  email: luuanzanchet@outlook.com
  url: https://luanzanchet.github.io
  github: https://github.com/luanzanchet
  twitter: https://twitter.com/luanzanchet
  facebook: https://facebook.com/luanzanchet
  linkedin: https://linkedin.com/in/luanzanchet

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
